version: '3'

services:
  web:
    build: .
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; flask run --host=0.0.0.0'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:5000
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/flaskdb
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:admin@db:5432/flaskdb
  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flaskdb
      - PGDATA=/var/lib/postgresql/data/pgdata