version: '3'

services:
  web:
    build: .
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host=0.0.0.0'
    volumes:
      - ./:/usr/src/core/
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/fast_db
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:admin@db:5432/fast_db
  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fast_db
      - PGDATA=/var/lib/postgresql/data/pgdata