version: '3'

services:
  web:
    build: .
    container_name: "fastapi"
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host=0.0.0.0 --port 8000'
    volumes:
      - ./:/usr/src/core/
    ports:
      - "8000:8000"
    environment:
      - ENV_STATE=test
  db:
    container_name: "db"
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fast_db
      - PGDATA=/var/lib/postgresql/data/pgdata